### ISSUE TITLE
Tweaks to get_coord_shares to run on Historical Data

### ISSUE THREAD

**Issue by rayms** [fabiogiglietto/CooRnet#11]
First, thanks for this new tool to detect coordination online. This is a suggestion for enhancement: 

Right now, `get_coord_shares` expects a dataframe that looks like the one returned from `get_ctshares`, but there are cases where you'd want to run `get_coord_shares` directly on a dataframe of historical data (from a List or Saved Search), but you can't because the function expects specific variables and returns errors like:

`Error: Can't subset columns that don't exist. x The columns account.id, account.handle, account.platform, account.platformId, and account.verified don't exist.`

A hack-y way to get around this is to modify the dataframe of historical data, and only then will `get_coord_shares`  produce the outputs: 

```
pro_trump <- read_csv("pro-trump-historical-data.csv")

pro_trump <- pro_trump %>%
add_count(link) %>%
mutate(id = row_number(),
       account.url = str_extract(url, "https://www.facebook.com/groups/[:digit:]+|https://www.facebook.com/[:graph:]+(?=\\/posts)"),
       account.platform = "facebook",
       account.platformId = NA,
       account.verified = NA,
       account.handle = NA) %>%
rename(expanded = link, account.id = facebook_id, ct_shares = n, date = created, account.subscriberCount = likes_at_posting, account.name = group_name) %>%
 select(-url)

get_coord_shares(pro_trump)
```
I think this would be a good addition for people who want to look for coordination directly in lists or saved searches they've curated. Cheers!

**Comment by fabiogiglietto** [comment]
This is a great idea and I clearly see the point in skipping the time consuming part of gathering the shares by querying the link API enpoint. This can be addressed in multiple ways. Let me think about it.

In the meantime...

Your workaround is brilliant! I would just add something along the line 37 of `get_urls_from_ct_histdata` to keep the expanded url only from the historical output.

**Comment by fabiogiglietto** [comment]
Hi Ray,
I've made quite a few experiments with different CT Historical CSV outputs.

I wrote this code that builds on your contribution to transform the CT CSV output in CoorNet ct_shares.df format.

`library(readr)
library(dplyr)

url <- "" # url to CT CSV
type <- ("Pages")

if (type=="Groups") {
  df <- read_csv(col_types = cols(
    .default = col_skip(),
    `Group Name` = col_character(),
    `User Name` = col_character(),
    `Facebook Id` = col_character(),
    `Likes at Posting` = col_number(),
    Created = col_character(),
    Type = col_character(),
    Likes =col_number(),
    Comments =col_number(),
    Shares =col_number(),
    Love =col_number(),
    Wow =col_number(),
    Haha =col_number(),
    Sad=col_number(),
    Angry=col_number(),
    Thankful=col_number(),
    URL = col_character(),
    Message = col_character(),
    Link = col_character(),
    `Final Link` = col_character(),
    `Link Text`=col_character(),
    Description=col_character(),
    `Overperforming Score`=col_number()),
    file = url)
} else {
  df <- read_csv(col_types = cols(
    .default = col_skip(),
    `Page Name` = col_character(),
    `User Name` = col_character(),
    `Facebook Id` = col_character(),
    `Likes at Posting` = col_number(),
    Created = col_character(),
    Type = col_character(),
    Likes =col_number(),
    Comments =col_number(),
    Shares =col_number(),
    Love =col_number(),
    Wow =col_number(),
    Haha =col_number(),
    Sad=col_number(),
    Angry=col_number(),
    Thankful=col_number(),
    URL = col_character(),
    Message = col_character(),
    Link = col_character(),
    `Final Link` = col_character(),
    `Link Text`=col_character(),
    Description=col_character(),
    `Overperforming Score`=col_number()),
    file = url)
}

ct_shares.df <- df %>%
  mutate(expanded = ifelse(is.na(`Final Link`), Link, `Final Link`),
         account.name = ifelse(type=="Groups", `Group Name`, `Page Name`),
         id = row_number(),
         account.url = stringr::str_extract(expanded, "https://www.facebook.com/groups/[:digit:]+|https://www.facebook.com/[:graph:]+(?=\\/posts)"),
         account.platform = "facebook",
         account.verified = NA,
         account.id = NA,
         title=NA,
         message=NA,
         link=NA,
         subscriberCount=NA,
         platformId=NA,
         platform=NA,
         is_orig=FALSE) %>%
  rename(type = Type,
         caption = `Link Text`,
         description = Description,
         date = Created,
         account.subscriberCount = `Likes at Posting`,
         postUrl = URL,
         account.handle = `User Name`,
         account.platformId = `Facebook Id`,
         score = `Overperforming Score`,
         statistics.actual.likeCount = Likes,
         statistics.actual.shareCount = Shares,
         statistics.actual.commentCount = Comments,
         statistics.actual.loveCount = Love,
         statistics.actual.wowCount= Wow,
         statistics.actual.hahaCount = Haha,
         statistics.actual.sadCount = Sad,
         statistics.actual.angryCount = Angry,
         statistics.actual.thankfulCount = Thankful) %>%
  select(id,
         date,
         type,
         title,
         caption,
         description,
         message,
         expanded,
         postUrl,
         subscriberCount,
         score,
         statistics.actual.likeCount,
         statistics.actual.shareCount,
         statistics.actual.commentCount,
         statistics.actual.loveCount,
         statistics.actual.wowCount,
         statistics.actual.hahaCount,
         statistics.actual.sadCount,
         statistics.actual.angryCount,
         statistics.actual.thankfulCount,account.id,
         account.name,
         account.handle,
         account.subscriberCount,
         account.url,
         account.platform,
         account.platformId,
         account.verified,
         is_orig)

output <- CooRnet::get_coord_shares(ct_shares.df=ct_shares.df, clean_urls = TRUE)`

However, the whole idea of CooRnet is to start the analysis from a set of URLs. Skipping the step where you collect social media shares from URLs by using a pre-made collection of social media shares is theoretically possible but, in my experiments, tend to produce too many weird results.

The get_ctshares plays an important role in discovering potential coordinated entities that would need to be discovered by other means when you start form a set of social media shares. On the other hand, using the CSV output of the new search function may be promising but I've not tested it.

Given all this, I'm inclined to encourage the dev team to focus on other features.

Nevertheless, I strongly invite you to run your own experiments and let me know what you think.
