### ISSUE TITLE
get_coord_shares throws error

### ISSUE THREAD

**Issue by networks1** [fabiogiglietto/CooRnet#12]
Running with a CSV downloaded from mediacloud explorer (attached)

> output <- get_coord_shares(df = ct_shares.df)
Error in get_coord_shares(df = ct_shares.df) : 
  unused argument (df = ct_shares.df)

[crimea.zip](https://github.com/fabiogiglietto/CooRnet/files/4493955/crimea.zip)

**Comment by fabiogiglietto** [comment]
CooRnet plays nicely with MediaCloud but before using `get_coord_shares` you need something like `ct_shares.df <- CooRnet::get_ctshares(urls = df,
                                      url_column = "url",
                                      date_column = "publish_date")`.

The idea is that you start from a set of URLs like the one you attached, use `ct_shares.df` to get the Facebook/Instagram shares from CrowdTangle and then use `get_coord_shares`.

You may find this [guide](http://coornet.org/tutorial00.html) useful.

**Comment by networks1** [comment]
I followed the docs.  I'm trying to get it to work with a .csv because the eventual goal is to get it to run with my own URLs.  Here is the whole session, using the variation of get_ctshares you suggested:

> library("CooRnet")
> df <- read.csv("crimea.csv")
> ct_shares.df <- CooRnet::get_ctshares(df, url_column = "url", date_column = "publish_date", platforms = "facebook,instagram", sleep_time = 1, nmax = 100, clean_urls = TRUE)
Loading required package: httr
Loading required package: jsonlite
Loading required package: tidyr
Loading required package: dplyr

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


  |                                                                                                          
  |                                                                                                    |   0%
  
[...]
|====================================================================================================| 100%> 
> output <- get_coord_shares(df = ct_shares.df)
Error in get_coord_shares(df = ct_shares.df) : 
  unused argument (df = ct_shares.df)

**Comment by fabiogiglietto** [comment]
You are almost there! The name of the parameter is `ct_shares.df` and not `df`.

`output <- CooRnet::get_coord_shares(ct_shares.df = ct_shares.df)`

**Comment by networks1** [comment]
You're welcome.  That change did the trick.  There is also typo in the docs:

# df <- read_csv("rawdata/MediaCloud_output.csv") # file exported from MediaCloud

Should be 

# df <- read.csv...

Thanks for sharing the code.

**Comment by fabiogiglietto** [comment]
Right again. I'll fix that too. Thanks :)

**Comment by networks1** [comment]
If you get a chance, it would be helpful to have the arguments for get_ctshares documented (at least the ones that aren't obvious).

**Comment by fabiogiglietto** [comment]
All the parameters are briefly documented in the help. See https://rdrr.io/github/fabiogiglietto/CooRnet/man/get_ctshares.html.
