### ISSUE TITLE
Running the script in VSCode doesnt produce any result

### ISSUE THREAD

**Issue by artislg** [fabiogiglietto/CooRnet#14]
I made the script run under VSCODE on Windows using R 4.0.0.0 but at the moment of executing get_output(output) the script didnt  produced any result? 

I used the sample specified in the readme.

**Comment by fabiogiglietto** [comment]
Hi, we haven't tested yet under R 4.0 specifically. Do you have an object called output in your environment as results of having executed `output <- get_coord_shares(ct_shares.df = ct_shares.df)`?

**Comment by fabiogiglietto** [comment]
I've tested the package under r 4.x and it works as expected.

**Comment by artislg** [comment]
Seems to be working fine in R 4.0.

Here's the output object in RStudio 

![image](https://user-images.githubusercontent.com/63132766/80990577-262d4f00-8dfc-11ea-86b0-5164e07ad480.png)

I think the next will be to plot/save to file such results. Any recommendation about what would be the best saving format?

**Comment by fabiogiglietto** [comment]
Well done! You can use `CooRnet::get_output` function to extract three object. The list of coordinated shares, the list of coordinated entities and respective graph. From there, if you need a visualization, I would export the graph file in graphml format (write.graph from igraph package).

**Comment by artislg** [comment]
Thank you so much for the help and the patience to explain this :)
