### ISSUE TITLE
Error 500 when consulting CT

### ISSUE THREAD

**Issue by artislg** [fabiogiglietto/CooRnet#20]
I downloaded latest version of the library and tried to run some URLs through the get_ctshares method, but I started receiving error 500 from it.

This is in the logs 

Unexpected http response code 500 on url with id 1
Unexpected http response code 500 on url with id 2

Any idea what might it be?

**Comment by fabiogiglietto** [comment]
response code 500 is internal server error. I guess CT servers are experiencing some temporary issue.

**Comment by artislg** [comment]
You are correct, there is a major outage in CT servers. Thank you
