### ISSUE TITLE
ctshares VS ct_shares_marked

### ISSUE THREAD

**Issue by estebanpdl** [fabiogiglietto/CooRnet#22]
Hello,
According to the CooRnet package, `ctshares ` refers to a "_data.frame of posts that shared the URLs and a number of variables returned_", while `ct_shares_marked` returns a "_data.frame that contains all the retrieved social media shares plus an extra boolean variable (is_coordinated) that identify if the shares were coordinated_."

Is there an explanation of why `ctshares` contains more records than `ct_shares_marked`? When I check shape/dimensions from such data.frames, `ctshares` is always bigger in size. Why are some records excluded?

Thank you,

**Comment by fabiogiglietto** [comment]
Are you using keep_ourl_only=TRUE?

**Comment by estebanpdl** [comment]
Hi, @fabiogiglietto.
Thanks for your answer.

I am keeping the default parameter:

`keep_ourl_only = FALSE`

The difference is minimum. For example, 4,722 records in `ctshares.df` after using the `get_ctshares` function, and 4,674 records in `ct_shares_marked.df` after using `get_coord_shares` with the parameter `keep_ourl_only = FALSE`.

I noticed the difference and I wondered about this variation.
