### ISSUE TITLE
Number of unique URLs shared in coordinated and non-coordinated way

### ISSUE THREAD

**Issue by estebanpdl** [fabiogiglietto/CooRnet#23]
Hello,
I found that the log.txt file shows two specific metrics:

- number of unique URLs shared in coordinated way
- number of unique URLs shared in non-coordinated way

It shows also the **Unique URLs in CT shares**.

When I double-checked these metrics in the csv file, I noticed that the number of unique URLs shared in a coordinated and non-coordinated way are represented by the `expanded` variable in the `ct_shares_markeddf` csv file, depending on the boolean result in the `iscoordinated` field.

However, these metrics show a percentage in the log.txt file. In my case:

- **number of unique URLs shared in coordinated way: 51 (21.52%)** 
- **number of unique URLs shared in non-coordinated way: 186 (78.48%)**

I noticed that some URLs in _non-coordinated_ are also in _coordinated_. In this example: the total unique URLs are 237 (51 + 186), but the script identified 222 ( **Unique URLs in CT shares** metric I mentioned above).

Is this beahavior normal?

Thank you!

**Comment by fabiogiglietto** [comment]
Hi Esteban,
you are right the log is a little misleading. While the link post is either coordinated or not (based on time and repetition), most of the URLs are shared through both coordinated and non coordinated posts (although in different proportion). Of course some URLs can be safely categorized as non coordinated insofar they have been shared by non coordinated posts only. The opposite is unlikely.

That said, I'll ask @nicolarighetti to modify the log process to make it more clear.

**Comment by estebanpdl** [comment]
Thank you so much for your answer, @fabiogiglietto
That would be very useful. The package is quite interesting and very helpful for research purposes.

Thanks a lot for this great work.

**Comment by nicolarighetti** [comment]
The problem was solved by specifying the number of unique URLs and the percentage of coordinated URLs over the total unique URLs in the log file. Can I close the issue?

**Comment by estebanpdl** [comment]
Thank you, @nicolarighetti 
Will update the package. I think this issue fixes the initial questions. 

best
