### ISSUE TITLE
Object 'account.handle' not found

### ISSUE THREAD

**Issue by josefslerka** [fabiogiglietto/CooRnet#25]
output <- CooRnet::get_coord_shares(ct_shares.df = ct_shares.df) 

produced error: 

building the graph...Error: Problem with `mutate()` input `account.handle.changed`.
x object 'account.handle' not found
ℹ Input `account.handle.changed` is `ifelse(length(unique(account.handle)) > 1, TRUE, FALSE)`.
ℹ The error occurred in group 1: account.url = "https://www.facebook.com/groups/1039932013048352".

**Comment by fabiogiglietto** [comment]
Hi Josef,
I'm unable to reproduce this error but you may want to make sure that you are using the latest version of CooRnet.
Let me know if the upgrade addressed the issue.

Best, Fabio
