### ISSUE TITLE
Error: Can't subset columns that don't exist. x Column `link` doesn't exist.

### ISSUE THREAD

**Issue by PiyushKyushu** [fabiogiglietto/CooRnet#26]
Hi,
Thank you for an interesting and useful package. 

I am trying to replicate the tutorial [http://coornet.org/index.html](url) on the dataset I collected from Crowdtangle.  successfully run the code and got the results till **Top URLs** section but I am getting below error when I am trying **Top Shares** section.

When I run this line `top_shares_per_components <- get_top_coord_shares(output, order_by = "engagement", component = TRUE, top = 10)`. I got the error 

> Error: Can't subset columns that don't exist. x Column `link` doesn't exist.

I don't understand why this section is having problem/error when **Top URLs** section is running smoothly? 

Can you please help solving this issue?

Thank you in advance!

**Comment by fabiogiglietto** [comment]
Hi :) thanks for pointing out this problem. We have identified and correct the error. Please update CooRnet to the latest version, restart r and let me know if it works.

Best, Fabio

**Comment by PiyushKyushu** [comment]
Thank you Fabio. Problem solved.

I am closing the issue. 

Thanks all who worked on creating this wonderful package.
