### ISSUE TITLE
Possible wrong value for calculating coordination interval quantile

### ISSUE THREAD

**Issue by ryanjgallagher** [fabiogiglietto/CooRnet#37]
Thanks for putting together this package! I was using the code to help myself better understand the CLSB method, and it really helped that the code is clear and commented usefully.

On [line 98](https://github.com/fabiogiglietto/CooRnet/blob/master/R/estimate_coord_interval.R#L98) of `estimate_coord_interval.R`, the coordination interval is estimated from the prior filtering steps:
```
coordination_interval <- paste0(quantile(ranked_shares_sub$sec_from_first_share, p), " secs")
```

However, `p` is described as the "parameter that controls the percentage of total shares to be reached." In the following warning and the academic articles I've read, the final step seems to always be to calculate the median. Should the last call to `quantile` use `0.5` instead of `p`?

Since `p` defaults to `0.5`, the estimation still behaves as expected if no parameters are changed. But if the user varies `p` to control the percent of total shares reached, then I believe it will also change the quantile for the share times. As someone who is not typically an R user though, it's possible I've missed something, or that I've misunderstood the method.

**Comment by fabiogiglietto** [comment]
Hi Ryan,
thanks for taking the time to look at the CooRnet code.  And yes, your analysis is correct. In line 98 p should be 0.5. Thanks for pointing this out. I've now fixed the code.

**Comment by fabiogiglietto** [comment]
Do you mind if I close thi issue?
